name: locution-postgres
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=locution
      - POSTGRES_DB=locution
    expose:
      - 5432
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~