name: locution-telemetry
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus:/prometheus"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # - grafana:/var/lib/grafana
      # - ./grafana/provisioning/:/etc/grafana/provisioning/
      # - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yaml
      # - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

    expose:
      - 4000
    ports:
      - "4000:4000"
    depends_on:
      - prometheus

volumes:
  prometheus: ~
  grafana: ~